name: Docker Image Push
on:
  push:
    branches:
    - main
    - develop
jobs:
  linuxbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: Build and push Linux Docker image
      uses: docker/build-push-action@v7.2.0
      with:
        context: .
        file: Dockerfile.linux
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/dvop400final:linux-latest
  windowsbuild:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push Image
      shell: powershell
      run: |
        # Build the container tagged with the repository name
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dvop400final:windows-latest -f Dockerfile.windows .
        
        # Push the image to Docker Hub
        docker push ${{ secrets.DOCKER_USERNAME }}/dvop400final:windows-latest

        # Create a multi-platform manifest that includes both the Linux and Windows images
        docker buildx imagetools create --append -t ${{ secrets.DOCKER_USERNAME }}/dvop400final:latest ${{ secrets.DOCKER_USERNAME }}/dvop400final:latest ${{ secrets.DOCKER_USERNAME }}/dvop400final:latest-windows
        
    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v7.2.0
    #   with:
    #     context: .
    #     file: Dockerfile.windows
    #     platforms: windows/amd64
    #     push: true
    #     tags: ${{ env.TAG }}
